version: '2'
networks:
  mired2:
    ipam:
      config:
        - subnet: 182.28.0.0/16
          gateway: 182.28.0.1
services:
  db:
    image: bitnami/mongodb:latest
    container_name: mongo_DB
    networks:
      mired2:
         ipv4_address: 182.28.0.11
    ports:
      - "27017:27017"
    expose:
      - 27017
  app-tutorials:
    image: jparsu/tutorialesapi:5
    container_name: tutorialsapp
    networks:
      mired2:
        ipv4_address: 182.28.0.12
    expose:
      - 8082
    ports:
      - "8082:8082"
    depends_on:
      - db
  app-agenda:
    image: jparsu/agendaapi:1
    container_name: agendaapi
    networks:
      mired2:
        ipv4_address: 182.28.0.13
    expose:
      - 8080
    ports:
      - "8080:8080"
    depends_on:
      - db